name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "23"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: "10"
          run_install: false

      - name: Install markdownlint
        run: npm install -g markdownlint

      - name: Setup Mint
        uses: irgaly/setup-mint@v1

      - name: Add Mint bin to PATH
        run: |
          echo "$HOME/.mint/bin" >> $GITHUB_PATH

      - name: Install xcbeautify
        run: |
          mint install cpisciotta/xcbeautify

      - name: Install SwiftLint
        run: |
          mint install realm/SwiftLint

      - name: Lint
        run: make lint

      - name: Build JavaScript
        run: make js-build

      # Uncomment when SafariConverterLib V3 is pushed to Github and it can
      # be cloned & used to build.
      # - name: Build Swift
      #   run: make swift-build
