name: CI

on:
  push:
  pull_request:

env:
  SWIFT_VERSION: "6.0"
  NODE_VERSION: "23"
  PNPM_VERSION: "10"

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get swift version
        run: swift --version

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - name: Install markdownlint
        run: npm install -g markdownlint-cli

      - name: Setup Mint
        uses: irgaly/setup-mint@v1

      - name: Add Mint bin to PATH
        run: |
          echo "$HOME/.mint/bin" >> $GITHUB_PATH

      - name: Install xcbeautify
        run: |
          mint install cpisciotta/xcbeautify

      - name: Install SwiftLint
        run: |
          mint install realm/SwiftLint

      # Set up Swift after building&installing xcbeautify and SwiftLint
      # as xcbeautify won't build with Swift 6
      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: ${{ env.SWIFT_VERSION }}

      - name: Lint
        run: make lint

      - name: Build JavaScript
        run: make js-build

      # Uncomment when SafariConverterLib V3 is pushed to Github and it can
      # be cloned & used to build.
      # - name: Build Swift
      #   run: make swift-build
